version: "3.2"
services:
  database:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata/seed.sql:/docker-entrypoint-initdb.d/seed.sql
