---
micronaut:
  application:
    name: postgresql-extensions-micronaut

---
dataSource:
  pooled: true
  dbCreate: update
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres

hibernate:
  dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
  hbm2ddl:
    auto: update
  cache:
    queries: false


